### PR TITLE
Indicate the download status in the status bar

### PR DESCRIPTION
**Pull request by kaste**
The download size of "checkstyle" is currently above 10MB, downloading
thus can take a few seconds.

Although SublimeLinter will show a "waiting spinner", additionally
inform the user by flashing the status bar that a download is in
progress.

### CODE REVIEW

**Comment by kaste** [comment]
This is just an idea.

**Comment by LDAP** [comment]
Have a look at my feature branch show_progress. In my opinion there is no real benefit from flashing the status bar because it’s too short and a user may even miss it if the status bar is displaying the "Saved ..." message. 
Downside of my approach is the dependency of an external package.

**Comment by kaste** [comment]
I just don't know how dependencies work with hot-reloading to be honest.  Maybe a restart initially when installing is necessary; or whenever "requests" updates; or none at all because Package Control disables/enables this plugin in the correct order.  (This is also not trivial to test, though possible; I have outlined this for SublimeLinter itself https://github.com/SublimeLinter/SublimeLinter/wiki/Test-upgrade-locally)

Otherwise, of course a more sophisticated solution is better than the naive flashing here.

**Comment by LDAP** [comment]
Closed with #5

**Pull request closed without merging**
